### ISSUE TITLE
Changes to `.gitignore` between tags results in undetected dirty checkout

### ISSUE THREAD

**Issue by gin66** [arduino/libraries-repository-engine#194]
### Describe the problem

The library manager log is:
```
2023/05/08 21:17:39 Checking out tag: 0.28.4
2023/05/08 21:17:40 Release FastAccelStepper:0.28.4 already loaded, skipping
2023/05/08 21:17:40 Checking out tag: 0.29.0
2023/05/08 21:17:40 Release FastAccelStepper:0.28.4 already loaded, skipping
```

Why is the last line not 0.29.0 ?

### To reproduce

rerun library manager !?

### Expected behavior

Library manager updates FastAccelStepper to 0.29.0

### Additional context

I have checked arduino/library-registry#1552 stating wrong version in library.properties.
But the library.properties of the tagged commit is updated to 0.29.0
So arduino/library-registry#1552 does not apply

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/library-registry/issues?q=)
- [X] My report contains all necessary details

**Comment by JanBluePix** [comment]
On Linux I got today v0.28 with Flatpak install and v0.30 with appimageVersion.

**Comment by kuworking** [comment]
It looks I have been able to install v 0.30.0 with arduino IDE 2.0.3

![image](https://github.com/arduino/libraries-repository-engine/assets/4474004/14b4d365-2ada-4d38-861b-09475540c6d0)

**Comment by gin66** [comment]
Good to know. Stilll…the latest is 0.30.4 and not 0.30.0

As per [arduino library manager log](https://downloads.arduino.cc/libraries/logs/github.com/gin66/FastAccelStepper/), it has even stopped looking for new versions.

**Comment by gin66** [comment]
any news ?

**Comment by drf5n** [comment]
Still a problem:

<img width="272" alt="image" src="https://github.com/arduino/libraries-repository-engine/assets/2236516/1e9ef511-4ea4-4d9f-96f9-534b18154a12">

**Comment by cmlpreston** [comment]
Still a problem vs 0.30.12.

**Comment by gin66** [comment]
still a problem:

2024/09/04 06:17:49 Checking out tag: 0.31.0
2024/09/04 06:17:49 Release FastAccelStepper:0.30.0 already loaded, skipping

**Comment by cmaglie** [comment]
We have finally deployed a fix for this problem.
I checked all the versions/libraries reported here and the library manager triggered all the updates correctly.

If the problem persists, please open a new issue with fresh data.
Thank you!
