### ISSUE TITLE
Delete `production` branch

### ISSUE THREAD

**Issue by per1234** [arduino/libraries-repository-engine#20]
This can't be done via pull request, so I'll open an issue to host the proposal, discussion, and ruling.

[The repository's `production` branch](https://github.com/arduino/libraries-repository-engine/tree/production) has historically served two purposes:
- Host [the Library Manager index source list](https://github.com/arduino/libraries-repository-engine/blob/production/repositories.txt)
- A "release branch"

Since the list will now be stored in `arduino/library-registry`, the first purpose is now obsolete, so the question of the second purpose remains. I would suggest switching to using tags for versioning, reconfiguring the indexer job to check out the latest tag. That does not exclude the use of release branches, but I don't feel that this project has any need for that strategy.

**Comment by silvanocerza** [comment]
Yeah, I think using tags would be the best approach. Something like we do in the CLI repo I guess.

**Comment by rsora** [comment]
Approved

**Comment by per1234** [comment]
Done. Thanks for the input!
