### ISSUE TITLE
Arduino library repository including a submodule

### ISSUE THREAD

**Issue by jaenrig-ifx** [arduino/libraries-repository-engine#69]
Hi there, 

Not sure if this is the right place for this question. But I try :) 
Would if be feasible (from library manager process point of view) to have a repository following an the Arduino lib Spec, but including a git submodule in the "src" folder?

It will work when installing it by cloning recursively, but not sure if that would be supported when packaging the lib.

Thanks!

**Comment by per1234** [comment]
Hi @jaenrig-ifx. This is the tool that generates the archives installed by Library Manager from the library repositories, so this is the relevant repository.

As for whether it is supported, the answer is "no":
https://github.com/arduino/library-registry/blob/main/FAQ.md#are-git-submodules-supported
>#### Are Git submodules supported?
>No. The library archive distributed by Library Manager will only contain an empty folder where the submodule should be.

A little more information here:
https://github.com/arduino/Arduino/issues/6385#issuecomment-310406324

**Comment by jaenrig-ifx** [comment]
Thanks @per1234 for your quick reply :)
Crystal clear 👍
